### ISSUE TITLE
JRE Builds

### ISSUE THREAD

**Issue by lobax** [adoptium/temurin11-binaries#3]
Will there be JRE builds here, like with the [old AdotpOpenJDK releases](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.11+9)? If so, is there an ETA?

**Comment by lobax** [comment]
E.g. Right now there are only Windows x64 builds. There used to be builds for Mac, Linux, Windows x86 etc.

**Comment by karianna** [comment]
Yes see https://github.com/adoptium/adoptium/issues/68
