### ISSUE TITLE
jdk-11.0.14.1+1 can't work with AS  bumblebee patch2

### ISSUE THREAD

**Issue by bluecn2002** [adoptium/temurin11-binaries#7]
I have OS win 7 32bit.
using Temurin jdk-11.0.14.1+1 x86-32bits.
it can't work with android studio bumblebee patch2. exceptions happens when open as.
it CAN work with android studio Arctic Fox patch 2 or below.

**Comment by karianna** [comment]
Please post an issue with the full details in our adoptium-support repo.
